/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2023-03-13 01:39:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1661152496121L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/eclipse-workspace/bookShop01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/Administrator/eclipse-workspace/bookShop01/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bookShop01/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661148054800L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>아이디 찾기창</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".id_find_form {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	background: #E2E2E2;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".one {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-color: rgb(255, 215, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".two {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	border: none;\r\n");
      out.write("		color: #545454;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p1 {\r\n");
      out.write("	font-size: 2em;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".p2 {\r\n");
      out.write("	font-size: 1.2em;\r\n");
      out.write("	color: black;\r\n");
      out.write("	margin: 25px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".name {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	magin-top: 50px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin: 40px 0px 10px 0px;\r\n");
      out.write("	color: #6a6a6a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".email {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	magin-top: 30px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin: 20px 0px 80px 0px;\r\n");
      out.write("	color: #6a6a6a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".seamil {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	background-color: rgb(255, 215, 0);\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	magin: 25px 0px 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".putNum {\r\n");
      out.write("	width: 450px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	magin: 10px 0px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	color: #6a6a6a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".send {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	background-color: #2c2c2c;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom1 {\r\n");
      out.write("	border: none;\r\n");
      out.write("	background: #E2E2E2;\r\n");
      out.write("	margin-left: 400px;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	color: #545454;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom2 {\r\n");
      out.write("	border: none;\r\n");
      out.write("	background: #E2E2E2;\r\n");
      out.write("	margin-left: 30px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("	color: #545454;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"middle\">\r\n");
      out.write("		<img width=\"600px\" height=\"200px\" class=\"logo\" alt=\"booktopia\"\r\n");
      out.write("			src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/loginForm.png\">\r\n");
      out.write("		<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/addMember.do\">\r\n");
      out.write("			<input type=\"button\" value=\"아이디 찾기\" class=\"one\"><input\r\n");
      out.write("				type=\"button\" value=\"비밀번호 찾기\" class=\"two\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"id_find_form\" title=\"flex-direction:column\">\r\n");
      out.write("\r\n");
      out.write("				<h4 class=\"p1\">아이디 찾기</h4>\r\n");
      out.write("				<h4 class=\"p2\">아이디는 가입시 입력한 이메일로 찾을 수 있습니다.</h4>\r\n");
      out.write("\r\n");
      out.write("				<tr class=\"good\">\r\n");
      out.write("					<td><input type=\"text\" value=\"&nbsp&nbsp이름을 입력하세요.\"\r\n");
      out.write("						class=\"name\"></td>\r\n");
      out.write("					<td><input type=\"text\" value=\"&nbsp&nbsp이메일을 입력하세요.\"\r\n");
      out.write("						class=\"email\"></td>\r\n");
      out.write("					<td><input type=\"button\" value=\"이메일로 인증번호 보내기\" class=\"seamil\"></td>\r\n");
      out.write("					<td><input type=\"text\" value=\"&nbsp&nbsp인증번호를 입력해주세요\"\r\n");
      out.write("						class=\"putNum\"><input type=\"button\" value=\"인증\"\r\n");
      out.write("						class=\"send\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"button\" value=\"회원가입\" class=\"bottom1\"></td>\r\n");
      out.write("\r\n");
      out.write("					<td><input type=\"button\" value=\"로그인\" class=\"bottom2\"></td>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/memberForm.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/member/memberForm.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/memberForm.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
